name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
          persist-credentials: false # <--- this
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Get the version
        id: get_version
        run: |
          version=$(echo ${GITHUB_REF/refs\/tags\//} | cut -c 2-)
          echo ::set-output name=VERSION::$version
        shell: bash
      - run: make dep && make assembly

      - name : Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ralphc.zip
          path: target/scala-2.13/ralphc.jar

