name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
          persist-credentials: false # <--- this
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Get the version
        id: get_version
        run: |
          version=$(echo ${GITHUB_REF/refs\/tags\//} | cut -c 2-)
          echo ::set-output name=VERSION::$version
        shell: bash
      - run: make assembly

      - name : Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: aligner-artifact
          path: bin/

  release:
    name: release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
          persist-credentials: false # <--- this

      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Get the version
        id: get_version
        run: |
          version=$(echo ${GITHUB_REF/refs\/tags\//} | cut -c 2-)
          echo ::set-output name=VERSION::$version
        shell: bash
      - run: make assembly

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic   # 您需要一个`id`来使用输出变量
        with:
          branch: master
          extra_plugins: |
            conventional-changelog/conventional-changelog-jshint
            @google/semantic-release-replace-plugin
            @semantic-release/exec
            @semantic-release/changelog
            @semantic-release/git
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

